<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Boldness   
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20120422
-->

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>BIBLIOTECA</title>
<link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" /> 
<script type="text/javascript" src="<?php echo FW_PATH_LAYOUT; ?>jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="<?php echo FW_PATH_LAYOUT; ?>jquery.slidertron-1.0.js"></script>
	<link href="<?php echo FW_PATH_LAYOUT; ?>style.css" rel="stylesheet" type="text/css" media="screen" />
	<script src="<?php echo FW_SCAF_JAVASCRIPT; ?>jquery.js"></script>
	<script src="<?php echo FW_SCAF_JAVASCRIPT; ?>jquery.tablesorter.min.js"></script>
	<script src="<?php echo FW_SCAF_JAVASCRIPT; ?>jquery.tablesorter.pager.js"></script>
	<script src="<?php echo FW_SCAF_JAVASCRIPT; ?>sorttable.js"></script>
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#">Biblioteca</a></h1>
				<!-- <p>template design by <a href="http://www.freecsstemplates.org/">CSS Templates</a></p> -->
				<p>Sistema para gerencimento básico de uma biblioteca</p>
			</div>
		</div>
	</div>
	<!-- end #header -->
	<div id="menu">
		<ul>
			<li class="current_page_item"><a href="/biblioteca/cadastro/livros">Início</a></li>
			<!--
			<li><a href="#">Blog</a></li>
			<li><a href="#">Photos</a></li>
			<li><a href="#">About</a></li>
			<li><a href="#">Links</a></li>
			<li><a href="#">Contact</a></li>
			-->
		</ul>
	</div>
	<!-- end #menu -->
	<div id="page">
		<div id="content">
			<div id="slider">
			</div>

			<!-- <div class="post"> -->
				<!-- Neste código chamamos a VIEW que está na pasta VIEWS/NOME DO CONTROLADOR/ACTION -->
				<?php require_once(FW_VIEWS. "/". $this->_controller. "/". $nome. '.phtml'); ?>
			<!-- </div> -->

			<!-- 
			<div class="post">
				<h2 class="title"><a href="#">Welcome to Boldness</a></h2>
				<p class="meta">Posted by <a href="#">Someone</a> on April 22, 2012
					&nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
				<div class="entry">
					<p>This is <strong>Boldness</strong>, a free, fully standards-compliant CSS template designed by FreeCssTemplates<a href="http://www.nodethirtythree.com/"></a> for <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.  The picture in this template is from <a href="http://fotogrph.com/"><strong>FotoGrph</strong></a>.The gallery slider used in this template is powered by <strong><a href="http://nodethirtythree.com/">Slidertron</a></strong>. This free template is released under a <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attributions 3.0</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)</p>
					<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem.</p>
				</div>
			</div>
			
			<div class="post">
				<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
				<p class="meta">Posted by <a href="#">Someone</a> on April 19, 2012
					&nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
				<div class="entry">
					<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, consectetuer nisl felis ac diam. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. Mauris vitae nisl nec metus placerat consectetuer. </p>
				</div>
			</div>
			<div class="post">
				<h2 class="title"><a href="#">Phasellus pellentesque turpis </a></h2>
				<p class="meta">Posted by <a href="#">Someone</a> on April 15, 2012
					&nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">Full article</a></p>
				<div class="entry">
					<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc.</p>
				</div>
			</div>
			-->
			<div style="clear: both;">&nbsp;</div>
		</div>
		
		<!-- end #content -->
		<div id="sidebar-bg">
			<div id="sidebar">
				<ul>
					<li>
						<h2>System for library</h2>
						<p>
						O gerenciamento de uma biblioteca pode ser simplificado com o ajuda deste 
						software.
						</p>
						
						<p>
						Abaixo você pode acessar os cadastros do sistema.
						</p>
						
					</li>
					<li>
						<h2>Cadastros</h2>
						<ul>
							<li><a href="/biblioteca/cadastro/livros">Livros</a></li>
							<li><a href="/biblioteca/cadastro/usuarios">Usuários</a></li>
							<li><a href="/biblioteca/cadastro/emprestimos">Emprestimos</a></li>
						</ul>
					</li>
					
					
				</ul>
			</div>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer">
	<p>SISTEMA DE GERENCIAMENTO DE BIBLIOTECAS - MAIO DE 2012</p>
</div>
<!-- end #footer -->
</body>
</html>
